[package]
name = "ledger"
version = "0.1.0"
authors = ["Alberto Sonnino <alberto@sonnino.com>"]
edition = "2018"
publish = false

[[bin]]
name = "ledger"
path = "src/main.rs"

[dependencies]
store = { path = "../store" }
types = { path = "../types" }
serde = { version = "1.0.228", features = ["derive"] }
bincode = { version = "2.0.1", features = ["serde"] }
tokio = { version = "1.48.0", features = ["sync", "macros", "rt", "rt-multi-thread"] }
log = "0.4.29"
thiserror = "2.0.17"
ed25519-dalek = { version = "2.2.0", features = ["digest"] }

